seed: 42

dialog_tree:
  max_depth: 3
  question_expansion_factor: 3
  answer_expansion_factor: 1
  question_diverse_sample_count: 5  # Questions are generally naturally diverse so 5 samples should produce at least 2 clusters
  answer_diverse_sample_count: 5  # Answers are generally not very diverse, but when there is only one answer there is only one answer.
  inference_diverse_sample_count: 5

devices:
  clarification: [2]
  answer: [1]
  semantic_cluster: [3]

remote_vllm:
  clarification:
    port: 29002
    gpu_memory_utilization: 0.90
    max_lora_rank: 16
    max_model_len: 4096  #8192
    log_file: "clarification_vllm_remote.log"
  answer:
    port: 29003
    gpu_memory_utilization: 0.90
    max_lora_rank: 16
    max_model_len: 4096  #8192
    log_file: "answer_vllm_remote.log"

defaults:
  - _self_
  - clarification_model/base: qwen_3_vl_32b_merged_bfloat16
  - answer_model/base: qwen_3_vl_32b
  - answer_model/lora: qwen_3_vl_32b
  - semantic_cluster_model: bidirectional_entailment_clusterer

paths:
  data:
    trees_subpath: v2
  checkpoints:
    loras_subpath: v2/loras
    merged_models_subpath: v2/merged_models

runtime_meta:
  git_commit: null
  git_strict: true

wandb:
  project: "clarification-trees-generation"
  name: null
